### ISSUE TITLE
Do you have to rename to reshape-inheritance?

### ISSUE THREAD

**Issue by Shyam-Chen** [reshape/layouts#16]
https://pugjs.org/language/inheritance.html

**Comment by jescalan** [comment]
I wouldn't say I have to rename this, just because pug refers to a similar feature by a different name, no. Do you think that the current name is confusing and unclear to users? This is the only reason I'd consider renaming.

**Comment by Shyam-Chen** [comment]
The name is hard to know that it is extended.

**Comment by jescalan** [comment]
Ok, well if anyone else jumps in here and agrees I'd be a little more compelled to make the change. Otherwise I'm going to leave it.

Changing the name would be a enormous breaking change for everyone using the library, so it's only worth doing if it's a very important/critical issue and causes large numbers of users not to understand the library.

**Comment by Shyam-Chen** [comment]
`stale`
