### ISSUE TITLE
Relative paths are not well supported

### ISSUE THREAD

**Issue by msssk** [reshape/layouts#20]
Consider the following file structure:
```
views/
    app/
        view1.html
    layout.html
```

If `app/view1` extends `layout.html` with `src="./layout.html"` then `reshape-layouts` passes the wrong value for `options.root` at [line 43](https://github.com/reshape/layouts/blob/82af10cf6703dbfe3532e93b58aeb8558cbf013d/lib/index.js#L43). A potential fix is to pass a modified `options` object as the 2nd parameter to `handleExtendsNodes`:
```javascript
const layoutTree = handleExtendsNodes(parsedLayout, Object.assign({}, options, { root: path.dirname(layoutPath) }), ctx)
```

**Comment by jescalan** [comment]
See [my response to your other issue here](https://github.com/reshape/include/issues/27#issuecomment-339170880) -- this plugin behaves the same way. Again, open to changing this as a few people have found it to be confusing, but it would be a massively breaking change.

**Comment by HoldYourWaffle** [comment]
Is there a reason this hasn't been closed yet?

**Comment by jescalan** [comment]
I was sort of expecting more of a discussion on whether we should change this aspect of how things work, or at least for this to be a reference point for other people looking for the same, as several people have run into this same issue. It is very stale at this point though, so I'll close it out (unless you want to pick up the conversation thread and continue!)

**Comment by HoldYourWaffle** [comment]
**Big disclaimer: I have no idea what I'm talking about, I'm still mostly guessing how reshape works**

I'm not sure I completely understand the issue. If I understand correctly, the included/layout template gets passed some path that's relative to the original rendered file (from which it was referenced) instead of itself?

If that's the case I feel like your response to the other issue addresses it correctly. An include/layout is like a macro, it doesn't (and in my opinion shouldn't) have a separate context. I'm pretty sure PHP does that too (although I'm not sure how similar the meaning of 'context' is between PHP and reshape).

I personally prefer the `root` option over relative paths. Most importantly because relative paths can (and most likely will) get messy *very* quickly, especially when moving things. I also feel like it's less readable, it's much easier to 'interpret' a path from a known root folder instead of needing to resolve `../`'s in your head.

**Comment by jescalan** [comment]
Maybe I can explain it better here, let me give it a shot.

Let's say you had a folder structure like this:

```
root
  - views
    - folder1
      - index.html
    - layout.html
    - _header.html
```

```html
<extends src='../layout.html'>
  <block name='content'>
    <p>hello world</p>
  </block>
</extends>
```

And the layout looks like this:

```html
<!doctype html>
<body>
  <include src=''./_header.html></include>
  <block name='content'></block>
</body>
```

And the header is some basic partial. In this case, your `include` call would fail, because the layout is applied to the file, and the root path of the layout becomes the file's path. So you'd need to do `<include src='../_header.html'>` in order to have it resolve correctly. The potential fix here is to have anything rendered within the layout to use the layout's path as a relative root instead of the file's path. This would be a breaking change, but I wouldn't be opposed to adding it if there was enough support. In the past, there never was though, because as soon as someone ran into this, they typically decided, much like you have, to resolve from an absolute root rather than relative, and the problem was no longer relevant.

Also, I did a talk a while back where I kind of explain the context for reshape and walk through the basics of how it works, maybe this would be helpful. Definitely recommend 2x speed: https://www.youtube.com/watch?v=Pp9d4-bIDzk
